// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOikSA7ePwLH6wGPJegl5uIQXC8qslzKE',
    appId: '1:533582460117:web:dae7e7ec77cf3dd8f5de5c',
    messagingSenderId: '533582460117',
    projectId: 'flutter-starter-abcd',
    authDomain: 'flutter-starter-abcd.firebaseapp.com',
    storageBucket: 'flutter-starter-abcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlR4lb-eKwCyfWCzAGMRzBrxPgLAHE3E',
    appId: '1:533582460117:android:c3370aa332a9fb59f5de5c',
    messagingSenderId: '533582460117',
    projectId: 'flutter-starter-abcd',
    storageBucket: 'flutter-starter-abcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAREEIIGYsoRjtZoZoVzAILoyoAYJEUmaA',
    appId: '1:533582460117:ios:24a579cf92ca33d3f5de5c',
    messagingSenderId: '533582460117',
    projectId: 'flutter-starter-abcd',
    storageBucket: 'flutter-starter-abcd.appspot.com',
    iosClientId: '533582460117-5nt3h80etnlgq30gjlthhof9rp6gi9ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.starter',
  );
}
